import { LevelData } from "./types";

/**
 * Level definitions - these will be loaded from the database in production
 * For now, we define them here as defaults
 */

export const LEVEL_DEFINITIONS: Record<number, Omit<LevelData, "id">> = {
  1: {
    levelNumber: 1,
    name: "Getting Started",
    difficulty: "easy",
    targetTime: 30000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 200, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 400, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 600, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "goal",
        position: { x: 720, y: 300 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },

  2: {
    levelNumber: 2,
    name: "Moving Platforms",
    difficulty: "easy",
    targetTime: 45000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 200, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 120,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 100,
        moveDistance: 150,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 400, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 120,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 100,
        moveDistance: 150,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 600, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 120,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 120,
        moveDistance: 150,
        currentDistance: 0,
      },
      {
        type: "goal",
        position: { x: 720, y: 300 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },

  3: {
    levelNumber: 3,
    name: "Obstacle Course",
    difficulty: "medium",
    targetTime: 60000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 200, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "obstacle",
        position: { x: 220, y: 420 },
        velocity: { x: 0, y: 0 },
        width: 40,
        height: 40,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 80,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 400, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "obstacle",
        position: { x: 420, y: 350 },
        velocity: { x: 0, y: 0 },
        width: 40,
        height: 40,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 100,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 600, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 150,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "goal",
        position: { x: 720, y: 300 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },

  4: {
    levelNumber: 4,
    name: "Complex Challenge",
    difficulty: "hard",
    targetTime: 90000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 120,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 150, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 100,
        moveDistance: 120,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 180, y: 420 },
        velocity: { x: 0, y: 0 },
        width: 40,
        height: 40,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "down",
        moveSpeed: 80,
        moveDistance: 80,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 300, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "obstacle",
        position: { x: 330, y: 350 },
        velocity: { x: 0, y: 0 },
        width: 40,
        height: 40,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 120,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 450, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 90,
        moveDistance: 130,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 600, y: 270 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "goal",
        position: { x: 720, y: 230 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },

  5: {
    levelNumber: 5,
    name: "Extreme Difficulty",
    difficulty: "hard",
    targetTime: 120000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 130, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 80,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 120,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 160, y: 420 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 150,
        moveDistance: 120,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 260, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 80,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "down",
        moveSpeed: 100,
        moveDistance: 80,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 290, y: 350 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "up",
        moveSpeed: 130,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 390, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 80,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 110,
        moveDistance: 140,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 420, y: 280 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 140,
        moveDistance: 110,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 530, y: 270 },
        velocity: { x: 0, y: 0 },
        width: 80,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 660, y: 200 },
        velocity: { x: 0, y: 0 },
        width: 80,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "up",
        moveSpeed: 100,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "goal",
        position: { x: 720, y: 150 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },

  6: {
    levelNumber: 6,
    name: "The Final Boss",
    difficulty: "extreme",
    targetTime: 150000,
    width: 800,
    height: 600,
    gravity: 0.6,
    objects: [
      {
        type: "player",
        position: { x: 50, y: 500 },
        velocity: { x: 0, y: 0 },
        width: 30,
        height: 40,
        color: "#3b82f6",
        isActive: true,
        jumpPower: 15,
        moveSpeed: 200,
        health: 100,
        maxHealth: 100,
        isJumping: false,
        isGrounded: false,
      },
      {
        type: "platform",
        position: { x: 0, y: 550 },
        velocity: { x: 0, y: 0 },
        width: 100,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: false,
      },
      {
        type: "platform",
        position: { x: 130, y: 480 },
        velocity: { x: 0, y: 0 },
        width: 70,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 150,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 160, y: 420 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "down",
        moveSpeed: 160,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 200, y: 420 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "up",
        moveSpeed: 160,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 260, y: 410 },
        velocity: { x: 0, y: 0 },
        width: 70,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 140,
        moveDistance: 120,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 290, y: 350 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 150,
        moveDistance: 110,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 330, y: 350 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 150,
        moveDistance: 110,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 390, y: 340 },
        velocity: { x: 0, y: 0 },
        width: 70,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "up",
        moveSpeed: 130,
        moveDistance: 120,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 420, y: 280 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "down",
        moveSpeed: 160,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 530, y: 270 },
        velocity: { x: 0, y: 0 },
        width: 70,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "right",
        moveSpeed: 140,
        moveDistance: 130,
        currentDistance: 0,
      },
      {
        type: "obstacle",
        position: { x: 560, y: 210 },
        velocity: { x: 0, y: 0 },
        width: 35,
        height: 35,
        color: "#ef4444",
        isActive: true,
        isMoving: true,
        moveDirection: "left",
        moveSpeed: 150,
        moveDistance: 120,
        currentDistance: 0,
      },
      {
        type: "platform",
        position: { x: 660, y: 200 },
        velocity: { x: 0, y: 0 },
        width: 70,
        height: 50,
        color: "#8b5cf6",
        isActive: true,
        isMoving: true,
        moveDirection: "down",
        moveSpeed: 120,
        moveDistance: 100,
        currentDistance: 0,
      },
      {
        type: "goal",
        position: { x: 720, y: 150 },
        velocity: { x: 0, y: 0 },
        width: 50,
        height: 50,
        color: "#10b981",
        isActive: true,
        reached: false,
      },
    ],
  },
};
